/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 04.06.2026 19:20:36

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1488;
#else
constexpr int kTensorArenaSize = 464;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,126 } };
const TfArray<1, float> quant0_scale = { 1, { 0.096871256828308105, } };
const TfArray<1, int> quant0_zero = { 1, { 5 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(8) int32_t tensor_data1[3] = { -15, 11, 1, };
const TfArray<1, int> tensor_dimension1 = { 1, { 3 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00053886929526925087, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[3*10] = { 
  63, 15, 109, -99, -40, 56, 88, -112, -127, 90, 
  83, 74, -23, -81, -122, 11, 39, -92, 12, -23, 
  -108, -23, 127, -1, -113, -97, -106, -53, 118, 32, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 3,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0052460832521319389, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { 14, 0, 0, -7, 38, 0, -32, -7, 0, -19, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00039631681283935905, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  44, -82, -73, 14, 113, 17, 127, -111, -1, -51, 26, 20, 73, 126, 59, -89, 3, -28, -72, 27, 
  -61, -123, 73, 72, 58, -44, -56, -104, -100, 20, -56, -57, 68, 24, 75, 97, -54, 37, -48, -33, 
  -24, -104, -3, 113, -52, -64, -38, 22, -44, -12, 35, 55, -23, -93, -14, -75, 91, -105, -108, -87, 
  62, 15, 101, 26, -74, 83, -57, -49, -30, 72, 106, 52, -87, -102, -5, -48, -28, -57, 111, 96, 
  -51, 61, -104, -65, -96, 75, -45, 29, -103, 75, 95, 62, -13, 56, 23, -102, -51, 107, 81, 56, 
  -94, 76, -75, 55, -33, -126, -7, 84, -125, -51, 84, 64, -55, 67, -26, -73, -40, 67, -73, 4, 
  99, 49, -63, -87, 83, 85, 9, -39, -31, -1, 67, 44, -81, -48, 6, -19, 61, -20, -21, -41, 
  -18, 97, 50, 90, -11, 93, 103, -118, 123, -42, -65, 121, 62, -31, -109, 54, 94, 6, 11, 99, 
  67, 44, 59, 44, 94, 36, -117, -28, -32, 13, 102, 23, -5, -113, -37, 103, -94, 76, -51, -35, 
  46, -79, -17, -3, 84, 109, -24, 9, 81, -102, -66, 52, -83, -60, 58, -20, -22, 94, 1, 81, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0035540354438126087, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { -31, -16, 0, 3, -34, 0, 5, 24, -54, 119, -31, 0, 13, 49, -66, 0, -52, -29, 48, 22, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00020980421686545014, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*126] = { 
  -2, -16, -18, 73, 24, 48, 30, -56, 34, -71, 0, 36, -78, -57, -17, 84, 26, 70, -42, -41, 82, -25, 80, 14, -87, 56, -42, -42, -61, -80, 25, 31, 58, -73, -84, 43, -54, 69, -6, -57, 44, -5, -71, -28, -77, 73, -35, 84, -57, -63, -13, -83, 39, -17, -75, 62, 90, 72, 94, 57, 38, -34, 13, -68, -13, -62, -2, 27, 81, -9, 25, -75, -54, -21, -16, -47, 67, 46, -9, 79, 29, 0, -13, 31, -21, 8, -90, -14, -72, -83, 35, -18, -44, 80, -7, -85, 91, 52, -67, -33, -3, -90, 21, 50, -22, -39, -33, 6, -54, -47, 75, 29, 6, 62, -43, 87, -39, 34, -89, 32, 45, 5, 23, 88, -89, -14, 
  -86, -13, 79, 13, -22, 18, 32, 30, 43, 87, -57, 41, 15, 19, 59, -47, 74, 48, 96, -53, -13, -4, 80, -16, 46, 44, -14, 69, -20, -65, -12, 89, 82, 92, 65, -27, -71, -6, 27, -39, -36, -48, 93, 62, 51, -21, 65, -62, 10, 3, -82, -8, 6, -32, -10, -91, -85, 76, 79, -71, -14, 66, -35, -11, -23, 6, 67, -94, 53, -22, 86, -50, 58, -3, 16, 78, -26, -49, -3, 85, -9, -90, -45, 2, 44, 2, -13, -69, 16, -19, 32, 32, 86, 24, 8, 55, -41, -73, 18, -79, 22, 91, 2, -10, -61, 49, 72, -53, -17, -15, -23, -78, 94, 31, -23, 84, 27, 22, -66, -62, 26, -84, -26, -45, 46, -5, 
  60, -12, -79, -66, 40, -49, 57, 78, 88, -8, -70, 15, -67, 45, -54, 64, 30, 54, 1, 39, 92, -86, 51, -73, 11, -23, 88, 46, -48, -72, -47, 61, 47, -67, -18, -30, -79, -6, 53, -70, 47, 48, -86, -15, 33, -18, -48, -74, 33, -24, 47, -21, -17, -2, 48, -76, 10, 13, 11, -25, 85, -32, -15, 16, -25, 54, 19, -52, -28, -31, -5, -90, 7, 78, -16, -79, -78, 50, -45, -56, 38, -50, 33, -3, 8, 15, -23, -2, -73, 0, -65, 77, 21, -32, 92, 63, 29, 46, 32, 27, -89, -79, -47, -66, 42, -36, 81, 66, 8, -16, -44, 48, 7, -74, -57, -76, 44, 93, -21, 40, -47, 75, 93, -89, 81, 77, 
  -89, 53, -24, 53, -9, 45, -16, 89, 40, -81, 73, 71, 42, 56, 36, -24, -73, -46, 27, 55, -63, 40, -74, -72, 55, 47, -72, 49, 72, 57, -47, 38, 77, -45, 53, 9, 87, -90, 16, 62, -79, 52, -35, 89, 119, -105, -37, -79, 39, 28, -70, -9, -24, -98, 17, -75, -82, -94, -40, -14, 77, 26, 81, 32, -85, -42, 37, -104, -92, -114, 26, -76, -73, -87, 3, 15, -38, 77, 21, 77, 7, 44, 48, -42, -58, -90, 28, -48, 40, -79, -4, 2, -104, -12, 53, -57, -76, -39, 54, -40, -47, -30, 50, -77, -63, -14, 14, -10, 8, 11, -106, -3, -16, 50, -15, 71, -91, -8, 49, -25, -107, 61, -2, 17, -94, -19, 
  55, 40, 11, -68, -89, -74, 74, -25, -46, 52, -28, 16, -59, -42, -65, 49, 53, 60, -8, -22, -11, 63, -30, -6, -39, -8, 62, 58, -88, -76, 40, -62, 80, -69, -31, -47, -30, -87, 18, 52, 8, 26, -99, -29, 54, -74, 61, 53, -20, 61, 57, 66, -73, -25, -27, 88, 58, 70, 80, 53, -80, -75, 84, 68, 3, 40, -48, 80, -97, -29, -86, 19, 58, 27, 33, 38, -35, -30, -49, -41, 64, -93, 42, -70, 16, -49, 2, -76, 47, -40, -41, -2, 17, 55, 21, -2, 13, -24, -72, -76, -24, -85, 17, -31, 80, -69, -96, -43, -72, 13, -71, -15, -64, -12, 28, -15, -42, -69, -56, -18, 78, -32, -60, -17, -85, 1, 
  -28, 69, 16, -4, -31, -73, 9, 92, -36, 20, -86, -33, -91, 43, 16, -2, -84, 26, -29, 8, -72, -76, -9, -46, 68, -24, 25, -13, -44, 91, -18, -9, 72, -57, 21, -86, 63, -54, 38, 81, 63, 35, -64, -25, 16, -91, -69, -62, -3, 59, 81, -13, 31, -38, 41, 55, 31, -11, 52, 7, 24, -88, 61, -73, -26, -1, -34, 74, 80, 42, 86, -42, 63, -68, -92, -60, -11, -14, 59, 0, -72, 34, -46, 73, -8, -71, 27, -6, 91, -16, 11, 6, -57, 71, 4, -8, -11, 30, -2, 57, -13, 28, 75, -53, 20, 15, 90, -62, 32, 51, -10, -8, 28, 54, 65, 18, 45, -72, 25, -57, -92, 51, -71, 14, 4, 86, 
  30, -7, -34, -54, -63, -99, -37, 61, -38, 3, -8, -11, -3, 50, 32, -19, -41, -51, 87, 68, -48, 7, -59, 64, -40, -14, 85, -84, 68, 18, 57, -90, -4, -17, -77, 49, -88, 33, -79, 88, -14, 16, -31, 16, -35, -100, 75, -58, -16, -26, -67, 72, -85, 52, 26, -15, 4, 73, 47, -37, -62, 5, 62, -79, 36, 26, -89, 49, -81, -63, 4, 71, -38, 34, 17, 46, 34, 65, 32, -49, 61, 48, -4, 19, -80, -28, 48, 18, -52, -54, -80, 46, -48, 74, -40, -99, -53, -65, -91, -17, -64, -63, -5, -35, 80, -27, -22, -74, -55, -15, -22, 34, 48, -105, 11, -31, 41, -46, -89, -43, -60, 10, -86, -9, -45, -85, 
  78, -93, 5, 82, 83, 29, 27, 36, -29, 77, -21, 88, -34, 34, -61, -90, -32, -51, -63, 85, 76, -60, -39, 19, -18, 91, -25, 26, -87, -14, 21, 83, 18, -81, -35, -87, -17, 24, 62, -33, -18, 26, 127, 76, 7, 19, 52, -71, -49, 50, -61, -24, -17, 15, -29, -58, -81, 63, 60, -92, -62, -29, 48, -34, 64, -1, 37, -17, -30, 105, -46, 27, -9, 45, 5, 22, -30, 57, -45, 49, 95, -86, 60, 1, 62, -76, 18, 52, 78, -14, -5, -67, 24, -43, -67, -32, -23, -72, 10, 91, -23, 63, 6, -73, -5, -25, -45, -91, 95, -19, -42, -70, 20, 48, 86, -34, 72, -13, -30, 43, -22, 29, -9, -74, 41, 44, 
  36, 98, 67, -24, -89, 57, -11, -52, -6, -12, 10, 60, 57, -30, 17, -37, 42, -39, 94, 22, 88, 56, 75, 31, 48, 49, 66, -8, 78, -79, 53, -84, -10, 1, -74, -23, -79, 81, -58, 12, -44, -45, -111, -26, -51, 6, -55, -17, -52, 25, -86, -90, 94, -56, 49, 46, 15, 46, -6, -32, 60, -19, 80, -63, -12, -65, 63, 43, 46, -55, -46, -36, 10, -80, -32, -87, -71, -44, -54, 76, -48, -56, -76, -45, 50, 14, 9, 22, 41, 37, -15, -93, -92, -28, 65, -12, 79, 17, 36, -55, -67, -62, -49, 35, 6, 53, -29, 15, 12, -24, -49, 56, 13, 38, 67, 83, 29, -61, 73, -29, 59, 71, 4, -30, 44, -92, 
  -51, 20, -80, 13, -30, 55, -87, -5, -55, -98, -85, -69, -99, -30, -65, 67, -16, 48, 59, -65, -26, 85, 27, 81, 112, 84, 4, 26, -5, 39, -45, -31, -73, -7, 61, 23, 58, 65, -18, 9, 16, 33, -26, 17, -42, -71, 75, 36, 77, -76, 44, 83, -95, -93, -61, 12, 46, 4, -91, 22, -89, -57, -71, 93, 6, -18, -68, -2, -60, 42, -56, 64, 82, 3, -16, -70, 86, -26, -92, 64, 46, 88, -79, -53, -44, 72, -51, -31, 66, 22, 78, 39, -24, -10, 12, 85, -2, -86, -71, -42, 57, -72, -80, -34, 12, 22, -87, -22, 58, 60, 53, -44, -34, -37, 82, 63, 76, 53, 64, 48, 75, -89, -44, 81, -49, 43, 
  88, 19, 42, -92, -76, -34, 57, 18, -3, 34, -67, 31, 28, -69, 47, -51, 1, 2, 36, 23, -76, 42, -82, 69, 74, -18, -41, -26, 69, 66, -86, -71, -70, -17, 96, 85, -23, -70, -70, 29, 38, -9, 4, -29, -32, 62, 4, -85, 57, 39, -26, -55, -15, -3, 69, 85, -58, -36, 24, -12, 27, 34, 63, 60, 25, -87, -86, 38, 45, 29, 75, 13, -18, -35, 2, 85, 28, -55, 45, 95, -36, -61, 31, -60, -42, 60, -29, 21, -38, -44, 1, 90, 46, -46, -11, 8, -48, 36, -80, 47, 81, 60, 46, 41, 48, -46, 5, -83, 67, 4, -19, 6, 34, 47, -86, 15, -24, 82, -31, -51, -43, -75, -53, -67, 79, 46, 
  -13, 31, 82, -28, -71, -83, 92, -36, 68, -22, 80, 85, 59, 84, -34, 42, -39, -33, 84, 2, -21, -20, 89, 3, 28, 37, 59, 45, 94, 36, -8, -20, 4, -38, 25, -21, -64, 23, 24, 49, 41, 67, 80, -15, -49, -29, 21, 43, -80, -8, -69, 62, 28, 31, 85, 53, 47, -17, 10, -75, 70, 50, -3, -25, 66, 56, 60, -23, -19, -21, -72, 3, -52, -56, 74, 26, 40, 75, 41, 16, 42, 84, -77, -50, -87, -83, -60, 44, -11, 60, 46, -73, -90, -70, 17, 27, 41, 61, -15, -25, -12, -6, 70, 65, 57, 35, 9, 91, 0, -78, -19, 19, 38, 29, -84, -60, -86, 7, 58, 33, 92, 83, 6, -19, -7, -25, 
  -54, -72, -8, -34, 47, -87, -61, -96, -80, 39, -26, -90, 19, 45, -37, 64, 8, -36, 73, -29, 39, 37, -69, 70, 43, -35, 0, -51, 72, -30, -44, 17, -95, 78, 52, 53, 70, -66, -84, -63, -16, 10, -74, -40, -92, -40, 93, 49, -18, 89, 57, -86, -97, 13, -65, -95, -67, 24, -22, 37, -34, -71, -75, 64, 16, 9, 62, 33, 2, 57, -7, -50, 36, 54, 19, -98, -43, 65, -86, -86, 9, 35, 73, 54, 93, 74, -103, -53, 3, 51, -71, 77, 13, 9, -70, -89, 28, 4, 54, -26, -69, 49, 39, 25, -8, -89, -17, 57, 44, 8, -16, -41, -6, -54, -70, 6, -53, -38, 75, 42, 46, -17, 24, -57, 24, 32, 
  28, -85, -79, -2, 84, 84, -84, 78, -18, 14, 10, 19, 76, 18, -24, -72, -100, -22, -80, -40, -77, -80, -13, 0, -36, -92, -70, 73, -22, 0, 23, -99, -78, -96, -20, 16, 36, -14, 67, -36, 79, 39, 111, -75, 51, -17, 31, 56, 94, 57, 28, 39, -73, -49, 79, -42, 10, 58, 40, -22, -3, -36, -19, -35, 81, 42, 93, 96, 25, 91, -75, -13, 60, -17, 42, -69, -52, -45, 40, -57, -41, 40, -29, -34, 91, 27, 40, 94, 15, -78, 20, 24, -59, 51, -87, -65, -40, 89, 2, -47, 16, 83, 27, -65, -56, 42, -8, -27, -18, 52, 53, -93, -66, 21, -63, 43, 42, -59, 49, -83, -3, -40, -52, -36, 81, 18, 
  79, -73, -53, 11, 0, -50, -36, 37, 50, 36, 95, -86, -74, 95, -85, -30, -76, 18, 58, -68, 84, 83, -48, 73, -94, -60, -9, -71, 78, -21, 99, -45, -37, 63, -9, -56, -68, 27, 79, -80, -87, 82, -86, 55, -22, 58, -29, -53, -83, -33, -12, 47, 36, -10, -64, -54, 89, -17, 86, -47, 12, 45, -50, 87, 21, 73, 79, 62, -10, 54, 15, -51, 89, -32, 85, 49, -34, 29, 3, 13, 54, 15, -57, -38, 23, -69, 60, 4, -76, 24, -36, 35, -8, 58, -73, 3, 78, 78, 81, 100, -80, 91, -54, 75, -71, -39, 55, -91, -42, -58, -40, -1, 91, 52, -81, 60, 94, -75, 74, 81, -43, -8, -6, -51, -60, -68, 
  0, 78, -69, -87, -87, 25, -11, 15, 34, 31, -6, 36, -52, 43, 44, 72, 15, 41, 32, 55, -85, 78, -76, 41, 21, 1, -41, -34, -18, -51, 24, -32, -33, 49, -7, 20, 0, -86, 24, 82, 53, -44, 27, -66, 65, -57, -83, -23, -68, 64, 39, -8, 65, 79, 37, -53, 81, 41, -67, 78, 2, -58, 17, -40, 15, 38, 14, -55, 8, 60, -80, 76, 75, 80, 38, 66, -39, 21, 78, 35, -65, -55, 12, 87, 93, 71, 9, 48, 53, 93, -3, 92, 19, 59, 89, 65, -77, 46, 49, 42, 70, 80, 88, -28, 63, -58, 14, 37, 92, -53, 28, -79, -91, 16, 54, -59, -32, -81, -3, -10, -50, 18, -12, -33, 35, -22, 
  -17, -46, -19, -15, 65, -26, -33, -64, 33, -80, -79, -28, 23, 48, -31, 36, -71, -43, 42, -28, -76, -59, 23, -58, 30, -38, -19, 69, -66, 67, 32, 3, 76, -55, -27, -48, 28, -77, -39, 6, 2, -14, -21, 86, 18, -107, 37, -96, -15, -44, 3, -12, -17, -68, -12, -88, -12, -17, 62, -63, -60, 80, -54, -31, -88, 74, -20, -64, -21, 73, -90, -34, -60, 69, 61, 40, -51, 17, -62, 12, 14, 75, -101, -37, -45, 46, 31, -75, 65, -46, -12, 74, 71, 3, 2, -56, -2, -39, 71, -52, -22, -24, -29, -25, 72, 49, 45, 97, -30, -76, 36, 13, 57, -96, -95, 25, -30, 76, -61, -89, 34, -20, -59, -16, 78, 6, 
  -19, 47, 83, 63, 65, -26, -33, 80, 35, -9, -30, 93, -30, 69, -64, -28, -62, 27, 88, -48, 53, -42, -66, 90, -53, -74, -44, 33, -4, -51, -9, -67, 6, 26, 11, 94, 91, -47, 68, -75, -85, -24, 94, -29, 26, -61, 8, 91, -68, 48, -40, -51, 88, 52, 30, -66, 72, -78, -18, -42, 31, -70, 48, 88, -17, 46, -13, 2, 33, -23, 74, -31, 62, 87, 46, 25, -72, -66, 71, -69, -72, -82, -79, 19, 50, 84, -37, 19, 19, 44, 1, 92, -83, -44, 69, 51, 42, -30, 86, -82, 83, 40, 10, -54, -50, -96, -74, 85, 23, -93, -81, -40, 74, 6, -61, 30, 67, 94, -43, -10, -53, 87, 27, 85, 5, 42, 
  -60, -44, 61, -78, 64, 12, -58, -6, -1, -31, -85, -35, -79, -65, -69, -49, 6, -54, -51, 36, -47, 100, -40, 58, -29, -66, 1, -23, -80, -62, 44, -38, -57, -82, 93, 74, 27, -62, -70, -30, -67, 19, -55, 43, 5, -9, 84, 20, -74, -86, 5, -79, 42, -53, 59, -65, -60, -59, -26, 66, -30, -50, -63, 72, 41, -26, 85, -70, 8, 85, 61, 54, 73, -40, -84, 31, 87, 20, -23, 35, 30, 41, 83, 0, 36, 9, 101, 15, 2, -71, -86, 77, 62, -27, -64, -65, 53, 23, 90, -55, -91, 93, 23, 10, -45, 22, -37, -43, 15, 65, -53, 20, -84, -42, -47, -64, 48, 44, -76, -78, 84, -47, -19, 22, 31, 91, 
  6, 57, 18, -38, -4, -29, 29, -10, 67, 64, -74, 74, 64, 0, -1, -38, -2, -77, -50, 25, -35, -68, 77, -90, 0, 12, -58, -37, 34, 75, -65, 15, 80, -58, 9, 33, -84, 21, 7, -11, -60, -64, 6, 53, 15, -86, -110, 21, -12, 1, 23, 42, -79, 32, 43, -48, 50, -77, -63, 77, -73, 61, -70, 14, -80, 18, -18, -69, -69, -56, -90, 60, -28, -14, -20, 32, -77, -91, -80, -40, 72, -7, -3, -79, -46, 23, 104, -11, 24, -2, -90, 13, -64, -21, 26, -78, -63, -67, 92, -56, -30, 69, 61, -74, -18, 69, -80, -45, -4, 56, 97, 74, -75, -56, 42, 14, -5, -50, -40, -6, 92, 15, 43, -44, 28, 60, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,126 } };
const TfArray<1, float> quant6_scale = { 1, { 0.0021658046171069145, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.11151178181171417, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.10271840542554855, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,3 } };
const TfArray<1, float> quant9_scale = { 1, { 0.058481793850660324, } };
const TfArray<1, int> quant9_zero = { 1, { 127 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 126, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 12, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 30, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2520, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 128), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 3, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1014843_9_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1014843_9_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1014843_9_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1014843_9_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1014843_9_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
