/*
 * Copyright (c) 2026 EdgeImpulse Inc.
 *
 * Generated by Edge Impulse and licensed under the applicable Edge Impulse
 * Terms of Service. Community and Professional Terms of Service
 * (https://edgeimpulse.com/legal/terms-of-service) or Enterprise Terms of
 * Service (https://edgeimpulse.com/legal/enterprise-terms-of-service),
 * according to your product plan subscription (the “License”).
 *
 * This software, documentation and other associated files (collectively referred
 * to as the “Software”) is a single SDK variation generated by the Edge Impulse
 * platform and requires an active paid Edge Impulse subscription to use this
 * Software for any purpose.
 *
 * You may NOT use this Software unless you have an active Edge Impulse subscription
 * that meets the eligibility requirements for the applicable License, subject to
 * your full and continued compliance with the terms and conditions of the License,
 * including without limitation any usage restrictions under the applicable License.
 *
 * If you do not have an active Edge Impulse product plan subscription, or if use
 * of this Software exceeds the usage limitations of your Edge Impulse product plan
 * subscription, you are not permitted to use this Software and must immediately
 * delete and erase all copies of this Software within your control or possession.
 * Edge Impulse reserves all rights and remedies available to enforce its rights.
 *
 * Unless required by applicable law or agreed to in writing, the Software is
 * distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND,
 * either express or implied. See the License for the specific language governing
 * permissions, disclaimers and limitations under the License.
 */
// Generated on: 03.06.2026 20:58:27

#include <stdio.h>
#include <stdlib.h>
#include "edge-impulse-sdk/tensorflow/lite/c/builtin_op_data.h"
#include "edge-impulse-sdk/tensorflow/lite/c/common.h"
#include "edge-impulse-sdk/tensorflow/lite/micro/micro_mutable_op_resolver.h"
#include "edge-impulse-sdk/porting/ei_classifier_porting.h"

#if EI_CLASSIFIER_PRINT_STATE
#if defined(__cplusplus) && EI_C_LINKAGE == 1
extern "C" {
    extern void ei_printf(const char *format, ...);
}
#else
extern void ei_printf(const char *format, ...);
#endif
#endif

#define STRINGIZE(x) #x
#define STRINGIZE_VALUE_OF(x) STRINGIZE(x)

#if defined (__GNUC__)  /* GNU compiler */
#define ALIGN(X) __attribute__((aligned(X)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (_MSC_VER)
#define ALIGN(X) __declspec(align(X))
#elif defined (__TASKING__) /* TASKING Compiler */
#define ALIGN(X) __align(X)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ARMCC_VERSION) /* Arm Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__ICCARM__) /* IAR Compiler */
#define ALIGN(x) __attribute__((aligned(x)))
#define DEFINE_SECTION(x) __attribute__((section(x)))
#elif defined (__clang__) /* LLVM/Clang Compiler */
#define ALIGN(X) __ALIGNED(x)
#define DEFINE_SECTION(x) __attribute__((section(x)))
#endif

#if defined(EI_MODEL_SECTION) && (defined(__GNUC__) || defined(__clang__))
#define MODEL_SECTION(X) __attribute__((section(STRINGIZE_VALUE_OF(X))))
#else
#define MODEL_SECTION(X)
#endif

#ifndef EI_MAX_SCRATCH_BUFFER_COUNT
#ifndef CONFIG_IDF_TARGET_ESP32S3
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#else
#define EI_MAX_SCRATCH_BUFFER_COUNT 4
#endif // CONFIG_IDF_TARGET_ESP32S3
#endif // EI_MAX_SCRATCH_BUFFER_COUNT

#ifndef EI_MAX_OVERFLOW_BUFFER_COUNT
#define EI_MAX_OVERFLOW_BUFFER_COUNT 10
#endif // EI_MAX_OVERFLOW_BUFFER_COUNT

using namespace tflite;
using namespace tflite::ops;
using namespace tflite::ops::micro;

namespace {

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX) || defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
constexpr int kTensorArenaSize = 1488;
#else
constexpr int kTensorArenaSize = 464;
#endif

#if defined(EI_CLASSIFIER_ALLOCATION_STATIC)
#if defined (EI_TENSOR_ARENA_LOCATION)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) DEFINE_SECTION(STRINGIZE_VALUE_OF(EI_TENSOR_ARENA_LOCATION));
#else
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#endif
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX)
#pragma Bss(".tensor_arena")
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16);
#pragma Bss()
#elif defined(EI_CLASSIFIER_ALLOCATION_STATIC_HIMAX_GNU)
uint8_t tensor_arena[kTensorArenaSize] ALIGN(16) __attribute__((section(".tensor_arena")));
#else
#define EI_CLASSIFIER_ALLOCATION_HEAP 1
uint8_t* tensor_arena = NULL;
#endif

static uint8_t* tensor_boundary;
static uint8_t* current_location;

template <int SZ, class T> struct TfArray {
  int sz; T elem[SZ];
};

enum used_operators_e {
  OP_FULLY_CONNECTED, OP_SOFTMAX,  OP_LAST
};

struct TensorInfo_t { // subset of TfLiteTensor used for initialization from constant memory
  TfLiteAllocationType allocation_type;
  TfLiteType type;
  void* data;
  TfLiteIntArray* dims;
  size_t bytes;
  TfLiteQuantization quantization;
};

typedef struct {
  TfLiteTensor tensor;
  int16_t index;
} TfLiteTensorWithIndex;

typedef struct {
  TfLiteEvalTensor tensor;
  int16_t index;
} TfLiteEvalTensorWithIndex;

TfLiteContext ctx{};
static const int MAX_TFL_TENSOR_COUNT = 4;
static TfLiteTensorWithIndex tflTensors[MAX_TFL_TENSOR_COUNT];
static const int MAX_TFL_EVAL_COUNT = 4;
static TfLiteEvalTensorWithIndex tflEvalTensors[MAX_TFL_EVAL_COUNT];
TfLiteRegistration registrations[OP_LAST];

namespace g0 {
const TfArray<2, int> tensor_dimension0 = { 2, { 1,126 } };
const TfArray<1, float> quant0_scale = { 1, { 0.22589369118213654, } };
const TfArray<1, int> quant0_zero = { 1, { -28 } };
const TfLiteAffineQuantization quant0 = { (TfLiteFloatArray*)&quant0_scale, (TfLiteIntArray*)&quant0_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data1[4] = { 141, 355, -300, -36, };
const TfArray<1, int> tensor_dimension1 = { 1, { 4 } };
const TfArray<1, float> quant1_scale = { 1, { 0.00027468873304314911, } };
const TfArray<1, int> quant1_zero = { 1, { 0 } };
const TfLiteAffineQuantization quant1 = { (TfLiteFloatArray*)&quant1_scale, (TfLiteIntArray*)&quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data2[4*10] = { 
  70, 70, 120, -39, 10, -99, -127, -21, 120, 54, 
  66, -22, -93, -108, -90, -95, -1, 43, -44, 10, 
  -97, 103, -77, -111, 83, -96, 119, 56, 66, -69, 
  11, -22, 0, 57, 37, -53, 88, -41, -99, -116, 
};
const TfArray<2, int> tensor_dimension2 = { 2, { 4,10 } };
const TfArray<1, float> quant2_scale = { 1, { 0.0053563257679343224, } };
const TfLiteAffineQuantization quant2 = { (TfLiteFloatArray*)&quant2_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data3[10] = { -22, 0, 0, 35, -62, 0, -26, -54, 0, -63, };
const TfArray<1, int> tensor_dimension3 = { 1, { 10 } };
const TfArray<1, float> quant3_scale = { 1, { 0.00037454106495715678, } };
const TfLiteAffineQuantization quant3 = { (TfLiteFloatArray*)&quant3_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data4[10*20] = { 
  40, -92, -73, 14, 106, 17, 121, -116, -9, -58, 25, 20, 67, 122, 57, -90, -2, -29, -79, 25, 
  -61, -124, 74, 73, 58, -44, -57, -105, -101, 20, -57, -57, 68, 24, 76, 97, -54, 37, -48, -33, 
  -25, -105, -3, 114, -53, -64, -39, 22, -45, -12, 35, 55, -23, -94, -14, -76, 92, -106, -109, -88, 
  72, 22, 102, -5, -79, 83, -78, -45, -30, 80, 107, 53, -87, -100, 5, -49, -26, -57, 114, 98, 
  -59, 63, -105, -37, -97, 76, -34, 22, -107, 60, 97, 62, -28, 50, 22, -103, -59, 108, 73, 60, 
  -95, 76, -76, 55, -33, -127, -7, 85, -126, -51, 84, 65, -55, 68, -26, -74, -40, 67, -74, 4, 
  99, 71, -64, -77, 88, 85, 25, -37, -31, -2, 68, 44, -84, -43, 18, -19, 64, -19, -19, -25, 
  -27, 100, 51, 76, -10, 94, 110, -127, 118, -40, -63, 123, 70, -32, -111, 54, 89, 5, 12, 88, 
  68, 44, 60, 44, 95, 36, -118, -28, -32, 13, 103, 23, -5, -114, -37, 104, -95, 77, -52, -35, 
  36, -78, -17, -1, 81, 110, -29, 5, 77, -109, -65, 53, -88, -63, 55, -20, -27, 94, -3, 79, 
};
const TfArray<2, int> tensor_dimension4 = { 2, { 10,20 } };
const TfArray<1, float> quant4_scale = { 1, { 0.0035225402098149061, } };
const TfLiteAffineQuantization quant4 = { (TfLiteFloatArray*)&quant4_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int32_t tensor_data5[20] = { 14, -20, 0, -12, 15, 0, -31, 43, 16, 2, -13, 0, -2, -29, 7, 0, -16, -13, -22, -18, };
const TfArray<1, int> tensor_dimension5 = { 1, { 20 } };
const TfArray<1, float> quant5_scale = { 1, { 0.00048186079948209226, } };
const TfLiteAffineQuantization quant5 = { (TfLiteFloatArray*)&quant5_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const MODEL_SECTION(EI_MODEL_SECTION) ALIGN(16) int8_t tensor_data6[20*126] = { 
  3, -24, 6, 83, 33, 45, 26, -59, 29, -75, -3, 32, -84, -61, -22, 81, 22, 67, -47, -46, 78, -16, 76, 4, -81, 66, -44, -46, -65, -85, 19, 29, 56, -78, -89, 38, -60, 66, -10, -62, 40, -11, -89, -29, -47, 66, -54, 71, -70, -75, -23, -91, 34, -23, -81, 57, 87, 67, 90, 52, 33, -41, 6, -85, -32, -26, -2, 24, 64, -25, 14, -92, -67, -32, -24, -56, 60, 40, -15, 72, 23, -8, -22, 23, -47, 14, -68, -11, -68, -107, 10, -34, -58, 69, -19, -96, 83, 42, -78, -43, -14, -103, 7, 37, -34, -34, -24, 29, -51, -46, 76, 33, 10, 61, -50, 86, -38, 33, -92, 26, 37, 3, 24, 88, -95, -25, 
  -102, 8, 75, 5, -35, 11, 26, 27, 41, 86, -59, 39, 13, 18, 58, -50, 73, 47, 95, -55, -15, -23, 44, -4, 39, 34, -23, 63, -25, -72, -17, 86, 80, 90, 63, -30, -75, -9, 24, -43, -39, -53, 80, 83, 70, -41, 57, -69, 5, -1, -87, -12, 3, -35, -12, -94, -89, 74, 79, -73, -15, 65, -37, -32, -31, 17, 62, -104, 35, -41, 76, -65, 42, -15, 6, 68, -37, -60, -13, 77, -16, -100, -53, -6, 33, 0, -16, -76, 10, -41, 10, 17, 74, 15, -2, 47, -50, -83, 11, -87, 15, 85, -7, -18, -68, 31, 86, -63, -26, -28, -60, -108, 73, 12, -39, 70, 13, 9, -78, -75, 15, -94, -36, -56, 36, -18, 
  61, -12, -80, -67, 41, -49, 58, 79, 90, -8, -71, 15, -68, 45, -55, 65, 30, 55, 1, 40, 93, -87, 52, -74, 11, -24, 90, 46, -48, -73, -47, 62, 48, -68, -18, -31, -80, -6, 54, -72, 48, 49, -87, -16, 34, -18, -49, -75, 33, -24, 48, -21, -17, -2, 49, -77, 10, 13, 11, -26, 86, -32, -15, 16, -26, 54, 19, -53, -28, -31, -5, -91, 7, 79, -16, -80, -79, 51, -46, -56, 39, -51, 34, -3, 8, 16, -24, -2, -74, 0, -66, 78, 21, -33, 93, 64, 30, 47, 33, 27, -90, -81, -48, -67, 43, -37, 83, 67, 8, -16, -44, 49, 7, -75, -58, -78, 45, 95, -21, 40, -48, 76, 94, -90, 82, 78, 
  -83, 60, -54, 50, -15, 53, -11, 90, 46, -79, 76, 75, 46, 58, 40, -21, -71, -45, 31, 60, -61, 32, -68, -35, 53, 44, -70, 54, 77, 60, -42, 38, 79, -42, 56, 12, 92, -90, 18, 64, -77, 57, -2, 74, 93, -84, -3, -61, 56, 44, -61, -3, -18, -94, 22, -73, -80, -93, -38, -10, 85, 32, 89, 59, -73, -83, 49, -85, -62, -89, 53, -50, -53, -68, 19, 30, -26, 93, 31, 89, 18, 58, 65, -30, -26, -66, -20, -41, 51, -43, 34, 29, -80, 10, 76, -38, -58, -21, 71, -25, -32, -10, 73, -55, -43, -14, 1, -35, 13, 22, -87, 7, -10, 63, 2, 81, -89, 0, 61, -8, -90, 72, 0, 26, -82, 3, 
  80, 22, -11, -56, -71, -77, 72, -30, -49, 50, -33, 12, -64, -47, -70, 45, 49, 56, -13, -27, -15, 83, -27, 2, -30, 1, 59, 57, -92, -81, 37, -68, 77, -73, -35, -52, -35, -91, 15, 49, 4, 22, -70, -35, 38, -51, 80, 56, -20, 61, 56, 63, -78, -29, -30, 85, 54, 67, 77, 50, -84, -80, 81, 98, 10, 27, -39, 90, -94, -25, -82, 24, 62, 29, 33, 39, -35, -29, -51, -43, 64, -94, 44, -70, 48, -50, 2, -63, 67, -30, -32, 3, 22, 59, 26, 2, 17, -22, -72, -77, -22, -82, 22, -27, 81, -49, -84, -32, -60, 34, -70, -16, -68, -14, 29, -18, -46, -74, -58, -17, 80, -32, -64, -19, -86, 4, 
  -28, 70, 17, -4, -32, -74, 9, 94, -36, 20, -88, -34, -93, 44, 16, -2, -85, 27, -29, 8, -73, -78, -9, -47, 69, -24, 26, -13, -45, 93, -18, -10, 73, -57, 22, -88, 64, -55, 38, 82, 64, 36, -65, -26, 16, -92, -70, -63, -3, 60, 83, -14, 31, -38, 42, 56, 32, -12, 53, 7, 24, -90, 62, -74, -26, -1, -34, 75, 81, 42, 88, -42, 64, -69, -94, -61, -11, -14, 60, 0, -73, 35, -47, 74, -8, -72, 27, -6, 93, -17, 11, 6, -58, 72, 4, -8, -11, 30, -2, 58, -13, 29, 76, -54, 20, 15, 92, -63, 32, 52, -10, -8, 28, 54, 66, 18, 46, -73, 25, -58, -93, 52, -73, 14, 4, 87, 
  20, 2, -54, -66, -76, -100, -37, 62, -36, 5, -6, -9, 0, 53, 36, -16, -38, -50, 91, 72, -45, -8, -61, 70, -51, -25, 85, -85, 70, 19, 60, -90, -2, -15, -76, 53, -87, 37, -78, 91, -12, 19, -26, 25, -30, -101, 81, -52, -11, -21, -64, 76, -82, 57, 30, -11, 7, 78, 51, -33, -57, 10, 68, -77, 42, 3, -95, 47, -79, -61, 6, 75, -36, 36, 18, 47, 36, 67, 34, -49, 63, 51, -2, 21, -59, -17, 42, 16, -50, -49, -76, 50, -45, 79, -36, -96, -50, -62, -88, -14, -61, -59, 0, -30, 85, -41, -30, -91, -65, -22, -23, 33, 46, -107, 12, -33, 39, -48, -90, -43, -59, 10, -89, -11, -45, -83, 
  84, -110, 28, 91, 93, 27, 24, 34, -35, 73, -26, 86, -39, 30, -67, -96, -37, -56, -70, 82, 72, -40, -32, -34, -6, 109, -24, 26, -91, -15, 18, 83, 16, -86, -39, -91, -20, 20, 59, -36, -21, 22, 109, 74, 8, 11, 42, -81, -58, 42, -68, -30, -23, 8, -36, -65, -87, 59, 56, -99, -71, -37, 41, -48, 59, 1, 38, -22, -32, 108, -51, 23, -12, 42, 2, 19, -34, 55, -48, 47, 92, -91, 56, -3, 34, -76, 32, 57, 81, -20, -11, -74, 17, -51, -75, -41, -33, -80, 4, 87, -30, 55, -3, -83, -11, -12, -79, -77, 103, -16, -34, -61, 30, 54, 88, -31, 76, -9, -32, 42, -26, 27, -7, -75, 39, 41, 
  59, 93, 30, -11, -75, 55, -15, -62, -11, -20, 1, 53, 50, -39, 11, -45, 35, -49, 89, 15, 82, 60, 83, 68, 59, 55, 61, -13, 73, -87, 49, -96, -19, -6, -81, -31, -87, 76, -67, 5, -52, -53, -61, -34, -105, 45, -11, -7, -46, 30, -87, -94, 91, -62, 45, 42, 8, 40, -13, -38, 58, -23, 77, -13, 19, -116, 88, 72, 66, -43, -35, -22, 20, -73, -29, -84, -68, -43, -54, 79, -47, -54, -72, -43, 107, 9, -21, 40, 58, 64, 14, -78, -78, -16, 77, -2, 89, 27, 45, -50, -63, -52, -36, 48, 13, 70, -13, -5, 31, 0, -47, 55, 8, 38, 72, 82, 24, -65, 74, -25, 66, 71, -2, -33, 48, -85, 
  -83, 32, -50, -6, -56, 57, -85, 3, -52, -93, -79, -64, -94, -23, -59, 75, -9, 57, 67, -59, -19, 69, 21, 61, 98, 72, 8, 30, -1, 44, -41, -23, -66, -2, 67, 30, 65, 72, -12, 15, 22, 40, -77, 23, -18, -113, 36, 31, 75, -79, 45, 88, -91, -89, -56, 17, 54, 10, -86, 28, -85, -53, -67, 45, -12, 10, -93, -30, -74, 32, -66, 54, 76, -2, -19, -74, 84, -29, -95, 63, 46, 88, -84, -57, -98, 74, -42, -55, 41, 4, 60, 28, -34, -18, 4, 79, -8, -94, -78, -46, 53, -80, -90, -42, 8, -3, -96, -20, 34, 27, 50, -44, -32, -38, 79, 65, 80, 56, 65, 45, 71, -91, -41, 83, -52, 37, 
  88, 24, 44, -93, -77, -35, 58, 18, -3, 34, -69, 31, 28, -70, 47, -52, 1, 2, 36, 23, -77, 41, -84, 72, 75, -20, -42, -27, 70, 67, -88, -72, -72, -18, 97, 86, -24, -71, -71, 29, 39, -9, 2, -27, -31, 62, 3, -87, 58, 39, -27, -56, -16, -3, 70, 86, -59, -37, 24, -12, 27, 35, 63, 60, 23, -89, -87, 39, 45, 29, 76, 13, -19, -36, 1, 86, 28, -57, 45, 96, -37, -62, 31, -61, -44, 60, -32, 21, -39, -46, 0, 90, 46, -47, -11, 8, -50, 36, -81, 47, 81, 60, 46, 42, 48, -47, 5, -88, 68, 4, -21, 5, 34, 47, -88, 15, -25, 83, -32, -52, -44, -76, -54, -68, 80, 47, 
  -13, 32, 84, -29, -72, -84, 94, -37, 69, -22, 81, 87, 60, 86, -35, 43, -39, -33, 85, 3, -21, -20, 90, 3, 29, 37, 59, 46, 95, 36, -8, -20, 4, -39, 25, -21, -65, 24, 24, 50, 41, 68, 81, -15, -50, -29, 21, 44, -81, -8, -70, 63, 29, 32, 86, 54, 47, -17, 10, -76, 72, 50, -3, -26, 67, 56, 61, -23, -19, -22, -73, 3, -53, -57, 75, 26, 41, 76, 41, 16, 42, 85, -79, -51, -88, -84, -61, 44, -11, 61, 47, -74, -92, -71, 18, 27, 41, 62, -16, -25, -12, -6, 71, 66, 58, 36, 9, 92, 0, -80, -20, 20, 38, 29, -85, -61, -87, 7, 59, 33, 93, 84, 6, -19, -7, -25, 
  -44, -77, -29, -33, 54, -85, -59, -97, -78, 41, -25, -89, 21, 47, -35, 67, 10, -35, 77, -28, 43, 44, -63, 81, 44, -37, 1, -50, 75, -28, -41, 18, -95, 82, 56, 56, 74, -64, -82, -61, -13, 13, -47, -44, -122, -20, 117, 61, -8, 99, 65, -83, -94, 17, -63, -93, -66, 27, -19, 41, -31, -67, -72, 91, 33, -10, 69, 44, 18, 73, 5, -36, 48, 64, 26, -92, -36, 71, -83, -81, 14, 42, 82, 62, 127, 66, -107, -52, 3, 74, -47, 94, 26, 22, -59, -80, 38, 14, 65, -18, -60, 61, 54, 38, 3, -82, -11, 52, 49, 19, -15, -44, -10, -54, -65, 9, -54, -38, 78, 48, 55, -14, 24, -56, 28, 42, 
  14, -85, -56, -14, 75, 95, -75, 92, -8, 27, 23, 30, 89, 30, -13, -62, -89, -10, -71, -30, -66, -84, -9, -23, -48, -102, -61, 84, -12, 12, 34, -87, -66, -86, -8, 28, 48, -2, 81, -24, 93, 51, 73, -64, 69, -53, -6, 59, 100, 63, 36, 50, -64, -40, 91, -32, 21, 71, 53, -11, 6, -26, -10, -77, 70, 57, 71, 70, 22, 93, -75, -14, 63, -14, 48, -65, -47, -40, 48, -51, -35, 46, -23, -27, 49, 20, 54, 74, -12, -89, 11, 24, -60, 55, -86, -63, -37, 93, 5, -43, 22, 87, 29, -64, -52, 31, -1, -21, -33, 33, 54, -91, -61, 27, -60, 52, 52, -53, 55, -80, 0, -33, -41, -29, 87, 20, 
  92, -93, -35, 23, 12, -50, -37, 38, 47, 36, 94, -91, -78, 94, -90, -34, -82, 15, 55, -72, 81, 104, -38, 48, -82, -46, -6, -71, 79, -21, 98, -46, -38, 62, -11, -59, -72, 25, 79, -83, -91, 79, -111, 53, 4, 53, -52, -63, -93, -42, -19, 43, 32, -15, -70, -60, 87, -21, 83, -53, 5, 39, -57, 68, 8, 107, 79, 55, -15, 54, 11, -56, 87, -36, 86, 49, -35, 28, 1, 12, 53, 14, -61, -42, -16, -59, 83, 9, -74, 16, -47, 30, -14, 54, -79, -2, 74, 74, 76, 96, -85, 87, -63, 67, -79, -24, 49, -70, -34, -52, -30, 10, 103, 59, -79, 67, 102, -71, 78, 83, -44, -6, 0, -48, -60, -70, 
  0, 80, -70, -89, -88, 26, -12, 15, 34, 31, -6, 36, -53, 44, 44, 73, 16, 42, 33, 56, -86, 79, -77, 41, 22, 1, -42, -34, -18, -52, 25, -33, -34, 49, -7, 20, 0, -87, 24, 83, 54, -45, 28, -67, 66, -58, -85, -24, -69, 65, 39, -8, 66, 80, 38, -54, 82, 41, -69, 79, 2, -59, 17, -41, 15, 38, 15, -56, 8, 61, -81, 77, 76, 81, 39, 68, -40, 21, 79, 35, -66, -55, 13, 89, 94, 72, 9, 49, 54, 94, -3, 93, 19, 60, 90, 66, -78, 46, 50, 43, 71, 82, 90, -29, 64, -59, 14, 37, 93, -54, 28, -80, -92, 17, 55, -59, -32, -82, -3, -10, -50, 19, -12, -34, 35, -22, 
  -7, -40, -62, -13, 69, -28, -36, -73, 33, -85, -84, -32, 20, 45, -34, 33, -76, -49, 40, -32, -80, -73, 16, -11, 29, -47, -25, 65, -71, 63, 31, -5, 70, -59, -31, -53, 25, -82, -44, 1, -3, -18, 27, 79, -18, -77, 79, -85, -6, -36, 7, -12, -18, -69, -13, -90, -16, -21, 61, -65, -59, 82, -54, 12, -62, 28, -5, -45, -9, 81, -82, -24, -54, 76, 64, 44, -49, 21, -62, 13, 16, 80, -97, -34, 14, 58, -11, -64, 81, -26, 9, 88, 84, 13, 12, -46, 8, -31, 81, -47, -15, -12, -16, -12, 80, 52, 66, 69, -23, -62, 32, 5, 48, -102, -96, 20, -38, 72, -63, -88, 39, -21, -67, -20, 81, 12, 
  -22, 51, 85, 63, 65, -27, -35, 81, 35, -10, -31, 94, -31, 69, -65, -29, -63, 27, 89, -49, 53, -44, -72, 96, -55, -78, -46, 32, -5, -52, -10, -69, 6, 26, 11, 95, 92, -48, 69, -77, -87, -25, 91, -25, 25, -66, 5, 92, -69, 48, -41, -52, 90, 52, 30, -68, 73, -80, -18, -42, 31, -71, 48, 85, -21, 46, -14, -1, 32, -25, 74, -33, 62, 87, 45, 25, -74, -68, 71, -71, -74, -84, -81, 18, 46, 85, -41, 18, 17, 42, -1, 92, -86, -46, 69, 51, 42, -31, 86, -84, 84, 40, 9, -55, -52, -99, -74, 84, 21, -97, -88, -45, 72, 4, -63, 29, 66, 93, -46, -12, -55, 87, 26, 84, 3, 42, 
  -86, -31, 80, -97, 41, 15, -54, 1, 3, -26, -80, -30, -74, -59, -64, -42, 12, -48, -45, 43, -41, 82, -44, 48, -43, -80, 6, -19, -77, -58, 49, -32, -52, -78, 100, 81, 33, -58, -66, -25, -62, 26, -80, 50, 28, -33, 72, 19, -75, -87, 8, -76, 48, -49, 66, -61, -54, -53, -20, 73, -25, -45, -58, 50, 34, -14, 74, -83, -1, 79, 56, 48, 70, -42, -85, 32, 88, 21, -23, 37, 32, 43, 84, -1, 18, 16, 104, 1, -12, -89, -105, 70, 57, -32, -70, -70, 51, 21, 89, -56, -95, 90, 18, 5, -47, -1, -43, -48, -3, 42, -52, 26, -78, -40, -48, -61, 54, 49, -74, -79, 84, -45, -14, 26, 32, 90, 
  -6, 68, 26, -49, -19, -24, 34, -5, 73, 70, -70, 80, 70, 5, 4, -33, 3, -73, -45, 31, -31, -88, 86, -80, -10, 0, -54, -33, 40, 81, -61, 20, 86, -53, 14, 38, -81, 26, 12, -7, -57, -60, 13, 59, 33, -85, -101, 27, -7, 6, 28, 48, -75, 37, 49, -43, 56, -74, -58, 83, -69, 68, -65, 21, -78, 32, -22, -72, -66, -55, -88, 65, -24, -9, -15, 38, -73, -87, -76, -36, 78, -2, 1, -76, -33, 29, 101, -15, 22, -3, -93, 17, -61, -17, 31, -74, -59, -63, 98, -52, -26, 74, 66, -70, -14, 56, -72, -56, -12, 50, 116, 90, -65, -48, 48, 21, 2, -44, -34, -1, 98, 21, 50, -39, 34, 64, 
};
const TfArray<2, int> tensor_dimension6 = { 2, { 20,126 } };
const TfArray<1, float> quant6_scale = { 1, { 0.002133130794391036, } };
const TfLiteAffineQuantization quant6 = { (TfLiteFloatArray*)&quant6_scale, (TfLiteIntArray*)&g0::quant1_zero, 0 };
const TfArray<2, int> tensor_dimension7 = { 2, { 1,20 } };
const TfArray<1, float> quant7_scale = { 1, { 0.10632698237895966, } };
const TfArray<1, int> quant7_zero = { 1, { -128 } };
const TfLiteAffineQuantization quant7 = { (TfLiteFloatArray*)&quant7_scale, (TfLiteIntArray*)&quant7_zero, 0 };
const TfArray<2, int> tensor_dimension8 = { 2, { 1,10 } };
const TfArray<1, float> quant8_scale = { 1, { 0.051283050328493118, } };
const TfLiteAffineQuantization quant8 = { (TfLiteFloatArray*)&quant8_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfArray<2, int> tensor_dimension9 = { 2, { 1,4 } };
const TfArray<1, float> quant9_scale = { 1, { 0.075303159654140472, } };
const TfArray<1, int> quant9_zero = { 1, { -2 } };
const TfLiteAffineQuantization quant9 = { (TfLiteFloatArray*)&quant9_scale, (TfLiteIntArray*)&quant9_zero, 0 };
const TfArray<1, float> quant10_scale = { 1, { 0.00390625, } };
const TfLiteAffineQuantization quant10 = { (TfLiteFloatArray*)&quant10_scale, (TfLiteIntArray*)&g0::quant7_zero, 0 };
const TfLiteFullyConnectedParams opdata0 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs0 = { 3, { 0,6,5 } };
const TfArray<1, int> outputs0 = { 1, { 7 } };
const TfLiteFullyConnectedParams opdata1 = { kTfLiteActRelu, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs1 = { 3, { 7,4,3 } };
const TfArray<1, int> outputs1 = { 1, { 8 } };
const TfLiteFullyConnectedParams opdata2 = { kTfLiteActNone, kTfLiteFullyConnectedWeightsFormatDefault, false, false };
const TfArray<3, int> inputs2 = { 3, { 8,2,1 } };
const TfArray<1, int> outputs2 = { 1, { 9 } };
const TfLiteSoftmaxParams opdata3 = { 1 };
const TfArray<1, int> inputs3 = { 1, { 9 } };
const TfArray<1, int> outputs3 = { 1, { 10 } };
};

TensorInfo_t tensorData[] = {
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension0, 126, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant0))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data1, (TfLiteIntArray*)&g0::tensor_dimension1, 16, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant1))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data2, (TfLiteIntArray*)&g0::tensor_dimension2, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant2))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data3, (TfLiteIntArray*)&g0::tensor_dimension3, 40, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant3))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data4, (TfLiteIntArray*)&g0::tensor_dimension4, 200, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant4))}, },
{ kTfLiteMmapRo, kTfLiteInt32, (int32_t*)g0::tensor_data5, (TfLiteIntArray*)&g0::tensor_dimension5, 80, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant5))}, },
{ kTfLiteMmapRo, kTfLiteInt8, (int32_t*)g0::tensor_data6, (TfLiteIntArray*)&g0::tensor_dimension6, 2520, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant6))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 128), (TfLiteIntArray*)&g0::tensor_dimension7, 20, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant7))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension8, 10, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant8))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 16), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant9))}, },
{ kTfLiteArenaRw, kTfLiteInt8, (int32_t*)(tensor_arena + 0), (TfLiteIntArray*)&g0::tensor_dimension9, 4, {kTfLiteAffineQuantization, const_cast<void*>(static_cast<const void*>(&g0::quant10))}, },
};

#ifndef TF_LITE_STATIC_MEMORY
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#else
TfLiteNode tflNodes[4] = {
{ (TfLiteIntArray*)&g0::inputs0, (TfLiteIntArray*)&g0::outputs0, (TfLiteIntArray*)&g0::inputs0, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata0)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs1, (TfLiteIntArray*)&g0::outputs1, (TfLiteIntArray*)&g0::inputs1, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata1)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs2, (TfLiteIntArray*)&g0::outputs2, (TfLiteIntArray*)&g0::inputs2, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata2)), nullptr, 0, },
{ (TfLiteIntArray*)&g0::inputs3, (TfLiteIntArray*)&g0::outputs3, (TfLiteIntArray*)&g0::inputs3, nullptr, const_cast<void*>(static_cast<const void*>(&g0::opdata3)), nullptr, 0, },
};
#endif

used_operators_e used_ops[] =
{OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_FULLY_CONNECTED, OP_SOFTMAX, };


// Indices into tflTensors and tflNodes for subgraphs
const size_t tflTensors_subgraph_index[] = {0, 11, };
const size_t tflNodes_subgraph_index[] = {0, 4, };

// Input/output tensors
static const int in_tensor_indices[] = {
  0, 
};

static const int out_tensor_indices[] = {
  10, 
};


size_t current_subgraph_index = 0;

static void init_tflite_tensor(size_t i, TfLiteTensor *tensor) {
  tensor->type = tensorData[i].type;
  tensor->is_variable = false;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  tensor->allocation_type = tensorData[i].allocation_type;
#else
  tensor->allocation_type = (tensor_arena <= tensorData[i].data && tensorData[i].data < tensor_arena + kTensorArenaSize) ? kTfLiteArenaRw : kTfLiteMmapRo;
#endif
  tensor->bytes = tensorData[i].bytes;
  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  if(tensor->allocation_type == kTfLiteArenaRw){
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
      tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
  tensor->quantization = tensorData[i].quantization;
  if (tensor->quantization.type == kTfLiteAffineQuantization) {
    TfLiteAffineQuantization const* quant = ((TfLiteAffineQuantization const*)(tensorData[i].quantization.params));
    tensor->params.scale = quant->scale->data[0];
    tensor->params.zero_point = quant->zero_point->data[0];
  }

}

static void init_tflite_eval_tensor(int i, TfLiteEvalTensor *tensor) {

  tensor->type = tensorData[i].type;

  tensor->dims = tensorData[i].dims;

#if defined(EI_CLASSIFIER_ALLOCATION_HEAP)
  auto allocation_type = tensorData[i].allocation_type;
  if(allocation_type == kTfLiteArenaRw) {
    uint8_t* start = (uint8_t*) ((uintptr_t)tensorData[i].data + (uintptr_t) tensor_arena);

    tensor->data.data =  start;
  }
  else {
    tensor->data.data = tensorData[i].data;
  }
#else
  tensor->data.data = tensorData[i].data;
#endif // EI_CLASSIFIER_ALLOCATION_HEAP
}

static void* overflow_buffers[EI_MAX_OVERFLOW_BUFFER_COUNT];
static size_t overflow_buffers_ix = 0;
static void * AllocatePersistentBufferImpl(struct TfLiteContext* ctx,
                                       size_t bytes) {
  void *ptr;
  uint32_t align_bytes = (bytes % 16) ? 16 - (bytes % 16) : 0;

  if (current_location - (bytes + align_bytes) < tensor_boundary) {
    if (overflow_buffers_ix > EI_MAX_OVERFLOW_BUFFER_COUNT - 1) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d, does not fit in tensor arena and reached EI_MAX_OVERFLOW_BUFFER_COUNT\n",
        (int)bytes);
      return NULL;
    }

    // OK, this will look super weird, but.... we have CMSIS-NN buffers which
    // we cannot calculate beforehand easily.
    ptr = ei_calloc(bytes, 1);
    if (ptr == NULL) {
      ei_printf("ERR: Failed to allocate persistent buffer of size %d\n", (int)bytes);
      return NULL;
    }
    overflow_buffers[overflow_buffers_ix++] = ptr;
    return ptr;
  }

  current_location -= bytes;

  // align to the left aligned boundary of 16 bytes
  current_location -= 15; // for alignment
  current_location += 16 - ((uintptr_t)(current_location) & 15);

  ptr = current_location;
  memset(ptr, 0, bytes);

  return ptr;
}

typedef struct {
  size_t bytes;
  void *ptr;
} scratch_buffer_t;

static scratch_buffer_t scratch_buffers[EI_MAX_SCRATCH_BUFFER_COUNT];
static size_t scratch_buffers_ix = 0;

static TfLiteStatus RequestScratchBufferInArenaImpl(struct TfLiteContext* ctx, size_t bytes,
                                                int* buffer_idx) {
  if (scratch_buffers_ix > EI_MAX_SCRATCH_BUFFER_COUNT - 1) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d, reached EI_MAX_SCRATCH_BUFFER_COUNT\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffer_t b;
  b.bytes = bytes;

  b.ptr = AllocatePersistentBufferImpl(ctx, b.bytes);
  if (!b.ptr) {
    ei_printf("ERR: Failed to allocate scratch buffer of size %d\n",
      (int)bytes);
    return kTfLiteError;
  }

  scratch_buffers[scratch_buffers_ix] = b;
  *buffer_idx = scratch_buffers_ix;

  scratch_buffers_ix++;

  return kTfLiteOk;
}

static void* GetScratchBufferImpl(struct TfLiteContext* ctx, int buffer_idx) {
  if (buffer_idx > (int)scratch_buffers_ix) {
    return NULL;
  }
  return scratch_buffers[buffer_idx].ptr;
}

static const uint16_t TENSOR_IX_UNUSED = 0x7FFF;

static void ResetTensors() {
  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    tflTensors[ix].index = TENSOR_IX_UNUSED;
  }
  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    tflEvalTensors[ix].index = TENSOR_IX_UNUSED;
  }
}

static TfLiteTensor* GetTensorImpl(const struct TfLiteContext* context,
                               int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_TENSOR_COUNT; ix++) {
    // already used? OK!
    if (tflTensors[ix].index == tensor_idx) {
      return &tflTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_tensor(tensor_idx, &tflTensors[ix].tensor);
      tflTensors[ix].index = tensor_idx;
      return &tflTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_TENSOR_COUNT (%d)\n", MAX_TFL_TENSOR_COUNT);
  return nullptr;
}

static TfLiteEvalTensor* GetEvalTensorImpl(const struct TfLiteContext* context,
                                       int tensor_idx) {

  tensor_idx = tflTensors_subgraph_index[current_subgraph_index] + tensor_idx;

  for (size_t ix = 0; ix < MAX_TFL_EVAL_COUNT; ix++) {
    // already used? OK!
    if (tflEvalTensors[ix].index == tensor_idx) {
      return &tflEvalTensors[ix].tensor;
    }
    // passed all the ones we've used, so end of the list?
    if (tflEvalTensors[ix].index == TENSOR_IX_UNUSED) {
      // init the tensor
      init_tflite_eval_tensor(tensor_idx, &tflEvalTensors[ix].tensor);
      tflEvalTensors[ix].index = tensor_idx;
      return &tflEvalTensors[ix].tensor;
    }
  }

  ei_printf("ERR: GetTensor called beyond MAX_TFL_EVAL_COUNT (%d)\n", (int)MAX_TFL_EVAL_COUNT);
  return nullptr;
}

class EonMicroContext : public MicroContext {
 public:
 
  EonMicroContext(): MicroContext(nullptr, nullptr, nullptr) { }

  void* AllocatePersistentBuffer(size_t bytes) {
    return AllocatePersistentBufferImpl(nullptr, bytes);
  }

  TfLiteStatus RequestScratchBufferInArena(size_t bytes,
                                           int* buffer_index) {
  return RequestScratchBufferInArenaImpl(nullptr, bytes, buffer_index);
  }

  void* GetScratchBuffer(int buffer_index) {
    return GetScratchBufferImpl(nullptr, buffer_index);
  }
 
  TfLiteTensor* AllocateTempTfLiteTensor(int tensor_index) {
    return GetTensorImpl(nullptr, tensor_index);
  }

  void DeallocateTempTfLiteTensor(TfLiteTensor* tensor) {
    return;
  }

  bool IsAllTempTfLiteTensorDeallocated() {
    return true;
  }

  TfLiteEvalTensor* GetEvalTensor(int tensor_index) {
    return GetEvalTensorImpl(nullptr, tensor_index);
  }

};


} // namespace

TfLiteStatus tflite_learn_1014843_9_init( void*(*alloc_fnc)(size_t,size_t) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  tensor_arena = (uint8_t*) alloc_fnc(16, kTensorArenaSize);
  if (!tensor_arena) {
    ei_printf("ERR: failed to allocate tensor arena\n");
    return kTfLiteError;
  }
#else
  memset(tensor_arena, 0, kTensorArenaSize);
#endif
  tensor_boundary = tensor_arena;
  current_location = tensor_arena + kTensorArenaSize;

  EonMicroContext micro_context_;
  
  // Set microcontext as the context ptr
  ctx.impl_ = static_cast<void*>(&micro_context_);
  // Setup tflitecontext functions
  ctx.AllocatePersistentBuffer = &AllocatePersistentBufferImpl;
  ctx.RequestScratchBufferInArena = &RequestScratchBufferInArenaImpl;
  ctx.GetScratchBuffer = &GetScratchBufferImpl;
  ctx.GetTensor = &GetTensorImpl;
  ctx.GetEvalTensor = &GetEvalTensorImpl;
  ctx.ReportError = &MicroContextReportOpError;

  ctx.tensors_size = 11;
  for (size_t i = 0; i < 11; ++i) {
    TfLiteTensor tensor;
    init_tflite_tensor(i, &tensor);
    if (tensor.allocation_type == kTfLiteArenaRw) {
      auto data_end_ptr = (uint8_t*)tensor.data.data + tensorData[i].bytes;
      if (data_end_ptr > tensor_boundary) {
        tensor_boundary = data_end_ptr;
      }
    }
  }

  if (tensor_boundary > current_location /* end of arena size */) {
    ei_printf("ERR: tensor arena is too small, does not fit model - even without scratch buffers\n");
    return kTfLiteError;
  }

  registrations[OP_FULLY_CONNECTED] = Register_FULLY_CONNECTED();
  registrations[OP_SOFTMAX] = Register_SOFTMAX();

  for (size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].init) {
        tflNodes[i].user_data = registrations[used_ops[i]].init(&ctx, (const char*)tflNodes[i].builtin_data, 0);
      }
    }
  }
  current_subgraph_index = 0;

  for(size_t g = 0; g < 1; ++g) {
    current_subgraph_index = g;
    for(size_t i = tflNodes_subgraph_index[g]; i < tflNodes_subgraph_index[g+1]; ++i) {
      if (registrations[used_ops[i]].prepare) {
        ResetTensors();
        TfLiteStatus status = registrations[used_ops[i]].prepare(&ctx, &tflNodes[i]);
        if (status != kTfLiteOk) {
          return status;
        }
      }
    }
  }
  current_subgraph_index = 0;

  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1014843_9_input(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(in_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1014843_9_output(int index, TfLiteTensor *tensor) {
  init_tflite_tensor(out_tensor_indices[index], tensor);
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1014843_9_invoke() {
  for (size_t i = 0; i < 4; ++i) {
    ResetTensors();

    TfLiteStatus status = registrations[used_ops[i]].invoke(&ctx, &tflNodes[i]);

#if EI_CLASSIFIER_PRINT_STATE
    ei_printf("layer %lu\n", i);
    ei_printf("    inputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].inputs->size; ix++) {
      auto d = tensorData[tflNodes[i].inputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");

    ei_printf("    outputs:\n");
    for (size_t ix = 0; ix < tflNodes[i].outputs->size; ix++) {
      auto d = tensorData[tflNodes[i].outputs->data[ix]];

      size_t data_ptr = (size_t)d.data;

      if (d.allocation_type == kTfLiteArenaRw) {
        data_ptr = (size_t)tensor_arena + data_ptr;
      }

      if (d.type == TfLiteType::kTfLiteInt8) {
        int8_t* data = (int8_t*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes; jx++) {
          ei_printf("%d ", data[jx]);
        }
      }
      else {
        float* data = (float*)data_ptr;
        ei_printf("        %lu (%zu bytes, ptr=%p, alloc_type=%d, type=%d): ", ix, d.bytes, data, (int)d.allocation_type, (int)d.type);
        for (size_t jx = 0; jx < d.bytes / 4; jx++) {
          ei_printf("%f ", data[jx]);
        }
      }
      ei_printf("\n");
    }
    ei_printf("\n");
#endif // EI_CLASSIFIER_PRINT_STATE

    if (status != kTfLiteOk) {
      return status;
    }
  }
  return kTfLiteOk;
}

TfLiteStatus tflite_learn_1014843_9_reset( void (*free_fnc)(void* ptr) ) {
#ifdef EI_CLASSIFIER_ALLOCATION_HEAP
  free_fnc(tensor_arena);
#endif

  // scratch buffers are allocated within the arena, so just reset the counter so memory can be reused
  scratch_buffers_ix = 0;

  // overflow buffers are on the heap, so free them first
  for (size_t ix = 0; ix < overflow_buffers_ix; ix++) {
    ei_free(overflow_buffers[ix]);
  }
  overflow_buffers_ix = 0;
  return kTfLiteOk;
}
